image: "crystallang/crystal:0.36.1-alpine"

before_script:
  - apk --no-cache add libsodium bash openssl
  - shards install

cache:
  paths:
    - lib/

"spec & format":
  script:
    - crystal spec
    - crystal tool format --check

pages:
  stage: deploy
  script:
    - crystal docs -o public src/branca.cr
  artifacts:
    paths:
      - public
  only:
    - master
